# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 101eb4468ea33188e92d25835371e2cb9209eeffae5fd1371206a28f34df2e21ac26bfc0092d5331060025be224c13ebbbfdc445c17e839ed8def6abe12ca48d

test:
  secret_key_base: a9679ff0380e0a7059b51b0f14d36da67ae26eff610808342fdfe9f33989d5502ad0d7f20552f5591913f496f61ce8b87c85f4811289a7d700112091094e043b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
